@startuml
title <size:18>Module</size>

component userApl.exe as userApl <<C#>>
component WebAuthnModokiDesktop.dll as WebAuthnModokiDesktop <<C#>>
component SharedSecret.dll as SharedSecret <<C++>>
component crypto_43.dll as crypto <<openssl-2.7.4>>
component CBOR.dll as CBOR <<PeterO.Cbor.3.4.0>>
component Numbers.dll as Numbers <<PeterO.Numbers.1.1.2>>
component HidLibrary.dll as HidLibrary <<hidlibrary.3.2.46.0>>
component Newtonsoft.Json.dll as Newtonsoft.Json <<Newtonsoft.Json.12.0.1>>

userApl ..> WebAuthnModokiDesktop
WebAuthnModokiDesktop ..> SharedSecret
WebAuthnModokiDesktop ..> HidLibrary
WebAuthnModokiDesktop ..> CBOR
CBOR ..> Numbers
WebAuthnModokiDesktop ..> Newtonsoft.Json
SharedSecret ..> crypto

@enduml